version: 0.0
os: linux
files:
  - source: /        # Copy everything from the root of your repo
    destination: /home/ec2-user/app # Directory on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    
    - location: scripts/clean_up.sh  # Optional, clean up any unused Docker resources (old containers, volumes, etc.)
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user

    - location: scripts/run_tests.sh  # Run tests after installing dependencies
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/validate_docker.sh  # Script to validate if the container is running correctly
      timeout: 300
      runas: ec2-user

  #ValidateService:
    
