version: 0.0
os: linux
files:
  - source: / # Source can be the directory or the file location from CodePipeline artifacts
    destination: /home/ec2-user/myapp # Destination directory on the EC2 instance

hooks:
  AfterInstall:
    - location: scripts/run_docker.sh # Shell script that will run Docker commands
      timeout: 300
      runas: ec2-user # User under which to run the script
  ApplicationStart:
    - location: scripts/start_server.sh # Optionally, start the server
      timeout: 300
      runas: ec2-user
