version: 0.2

env:
  variables:
    DOCKER_FILE_PATH: "Dockerfile"

phases:
  install:
    commands:
      - echo "Installing bash..."
      - npm install -g snyk # Install Snyk CLI globally using npm

  pre_build:
    commands:
      - echo Authenticating with AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 954976319724.dkr.ecr.us-east-1.amazonaws.com
      - echo Building Docker image...
      - docker build -t 954976319724.dkr.ecr.us-east-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest -f $DOCKER_FILE_PATH . || { echo 'Docker build failed'; exit 1; }
      - echo "Running Snyk tests on Docker image..."
      - snyk auth $SNYK_TOKEN || { echo 'Snyk authentication failed'; exit 1; }
      - snyk config set disableSuggestions=true

  build:
    commands:
      - echo Running tests inside Docker container...
      # - docker run --rm $DOCKER_IMAGE_NAME
      # - snyk test --docker $DOCKER_IMAGE_NAME

  post_build:
    commands:
      - echo Monitoring Docker image with Snyk...
      # - snyk monitor --docker $DOCKER_IMAGE_NAME
      # - aws s3 cp snyk-report.json s3://$S3_BUCKET/snyk-reports/snyk-report-$(date +%Y%m%d%H%M%S).json
      - docker push 954976319724.dkr.ecr.us-east-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest

artifacts:
  files:
    - "**/*"
    - snyk-report.json

cache:
  paths:
    - "/root/.npm/**/*"
    - "/root/.docker/**/*"
