version: 0.2

env:
  variables:
    DOCKER_FILE_PATH: "Dockerfile"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install -g snyk

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 913524931303.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t 913524931303.dkr.ecr.us-east-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest -f $DOCKER_FILE_PATH .
      - echo "Running Snyk security scan..."
      - snyk auth $SNYK_TOKEN || { echo 'Snyk authentication failed'; exit 1; }
      - snyk config set disableSuggestions=true
      # Optional: - snyk test --docker 913524931303.dkr.ecr.us-east-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 913524931303.dkr.ecr.us-east-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest
      - echo "Generating imagedefinitions.json for CodePipeline ECS deployment..."
      - printf '[{"name":"app-container","imageUri":"913524931303.dkr.ecr.us-east-1.amazonaws.com/%s:latest"}]' $DOCKER_IMAGE_NAME > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - "/root/.npm/**/*"
